version: '3.5'

networks:
  pg-net:
    driver: bridge

services:
  postgres:
    container_name: pg
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - ./pg/data:/data/postgres
    ports:
      - 5432:5432
    networks:
      - pg-net
  
  pgadmin:
    container_name: pgadm
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    volumes:
      - ./servers/servers.json:/pgadmin4/servers.json
      - ./pg_storage:/var/lib/pgadmin/storage
    ports:
      - 5050:80
    networks:
      - pg-net